import { Language, Translations, ServicePackage, ServicePackageTranslations, AdditionalService } from './types';

export const WHATSAPP_NUMBER = "971501234567";
export const HOURLY_RATE_AED = 50;

export const LANGUAGES = {
  [Language.EN]: { nativeName: 'English', flag: '🇬🇧' },
  [Language.AR]: { nativeName: 'العربية', flag: '🇦🇪' },
};

export const COUNTRY_CODES = [
    { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪' },
    { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦' },
    { name: 'United Kingdom', code: '+44', flag: '🇬🇧' },
    { name: 'United States', code: '+1', flag: '🇺🇸' },
];

const enBase = {
  navHome: 'Home',
  navServices: 'Services',
  navWhyUs: 'Why Us',
  navLogin: 'Member Access',
  navLogout: 'Sign Out',
  heroTitle: 'Bespoke Cleaning for Dubai’s Premier Airbnbs',
  heroSubtitle: 'Elevating the standard of vacation rental hospitality with meticulous attention to detail and 5-star concierge quality.',
  heroCta: 'Initialize Booking',
  whyUsTitle: 'The NeatoCleaning Distinction',
  whyUsPoints: [
    { title: 'Quality Assurance', description: 'Every turnover is verified against a rigorous 50-point professional hospitality checklist.' },
    { title: 'Dynamic Scheduling', description: 'Our platform integrates seamlessly with your booking calendar for automated efficiency.' },
    { title: 'Premium Botanicals', description: 'Exclusively using high-grade, eco-conscious sanitization products for guest safety.' },
    { title: 'Certified Experts', description: 'Our hospitality professionals are extensively vetted, background-checked, and insured.' },
  ],
  servicesTitle: 'Specialized Service Tiers',
  servicesSubtitle: 'Precision-engineered solutions for the discerning short-term rental host.',
  getQuote: 'Request Quote',
  footerText: `© ${new Date().getFullYear()} NeatoCleaning UAE. Licensed by DTCM. All rights reserved.`,
  whatsappMessage: 'Greetings. I am interested in exploring your professional turnover services for my property.',
  whatsappTooltip: 'Need an instant quote? Chat with our concierge.',
  bookingTitle: 'Instant Service Estimate',
  serviceType: 'Cleaning Tier',
  bedrooms: 'Bedrooms',
  bathrooms: 'Bathrooms',
  kitchens: 'Kitchens',
  otherRooms: 'Lounge/Other',
  propertyDetails: 'Property Specifications',
  propertyRequirementsDesc: 'Define your property requirements for precise allocation.',
  estimatedPrice: 'Estimated Investment',
  bookNow: 'Proceed to Booking',
  howItWorksTitle: 'Our Streamlined Process',
  howItWorksSteps: [
      { title: 'Selection', description: 'Define your requirements and receive an immediate, transparent cost projection.' },
      { title: 'Confirmation', description: 'Finalize your details via our secure portal or directly with our concierge team.' },
      { title: 'Execution', description: 'Our professionals deliver a pristine environment, ensuring your property is guest-ready.' }
  ],
  testimonialsTitle: 'Host Experiences',
  testimonials: [
      { quote: 'NeatoCleaning has fundamentally transformed my operations. Their consistency and professionalism are truly elite.', author: 'Fatima Al M.', location: 'Dubai Marina Portfolio' },
      { quote: 'The attention to detail is remarkable. My Superhost status is largely thanks to their impeccable service standards.', author: 'Markus T.', location: 'Palm Jumeirah Host' },
      { quote: 'Efficient, reliable, and thorough. They understand the nuances of luxury hospitality perfectly.', author: 'Priya K.', location: 'Downtown Suites' }
  ],
  footerServices: 'Offerings',
  footerCompany: 'Enterprise',
  footerAbout: 'Our Story',
  footerContact: 'Concierge',
  footerFollow: 'Social Presence',
  loginTitle: 'Welcome Back',
  loginSubtitle: 'Authenticate your session via WhatsApp verification.',
  loginPhoneLabel: 'Contact Number',
  loginPhonePlaceholder: '50 123 4567',
  loginSendOtp: 'Send Verification Code',
  loginSendingOtp: 'Processing...',
  loginOtpTitle: 'Verify Identity',
  loginOtpSubtitle: 'Enter the secure code sent to your mobile device.',
  loginOtpLabel: 'Security Code',
  loginOtpPlaceholder: '123456',
  loginVerifyOtp: 'Authenticate',
  loginVerifyingOtp: 'Verifying...',
  loginSuccess: 'Authorized. Redirecting...',
  loginError: 'Authentication failed. Please re-verify your details.',
  bookingPageTitle: 'Finalize Service Request',
  bookingSummary: 'Service Summary',
  detailsLabel: 'Details',
  cleaningHours: 'Allocated Time',
  howManyHours: 'Duration (Hours)',
  numberOfProfessionals: 'Staff Count',
  haveCleaningMaterials: 'On-site Equipment Available?',
  yes: 'Yes, Provided',
  no: 'No, Required',
  specialInstructions: 'Property Notes / Access Codes',
  specialInstructionsPlaceholder: 'e.g. Access codes, parking spot, specific focus areas...',
  confirmBooking: 'Submit Inquiry',
  backToHome: 'Return',
  step1: 'Tier & Scale',
  step2: 'Enhancements',
  step3: 'Logistics',
  step4: 'Verification',
  step5: 'Success',
  customizeService: 'Refine Service',
  additionalServices: 'Add-on Services',
  scheduleAndDetails: 'Schedule & Logistics',
  reviewAndConfirm: 'Final Verification',
  nextStep: 'Continue',
  previousStep: 'Back',
  add: 'Select',
  added: 'Selected',
  scheduleYourCleaning: 'Appointment Logistics',
  selectDate: 'Preferred Date',
  selectTime: 'Arrival Window',
  address: 'Service Location',
  addressPlaceholder: 'Unit/Villa, Tower, Community Name',
  detectLocation: 'Use Current Location',
  detectingLocation: 'Locating...',
  detectLocationError: 'Location access restricted. Please input manually.',
  mapViewTitle: 'Service Zone Map',
  payment: 'Confirmation',
  paymentDetails: 'Contact Information',
  creditCard: 'Verified Account',
  cardName: 'Contact Name',
  cardNamePlaceholder: 'YOUR FULL NAME',
  cardNumber: 'WhatsApp Number',
  cardNumberPlaceholder: '50 123 4567',
  cardExpiry: 'Secondary Phone',
  cardExpiryPlaceholder: 'Optional',
  cardCVC: 'Email Address',
  cardCVCPlaceholder: 'manager@property.com',
  billingAddress: 'Inquiry Details',
  country: 'Region',
  countryPlaceholder: 'United Arab Emirates',
  streetAddress: 'Special Instructions',
  streetAddressPlaceholder: 'Anything else our team should know?',
  city: 'City',
  cityPlaceholder: 'Dubai',
  zipCode: 'Postal Code',
  zipCodePlaceholder: '00000',
  reviewYourBooking: 'Inquiry Submitted',
  totalPrice: 'Investment Total',
  cleaningDate: 'Date',
  cleaningTime: 'Time',
  extras: 'Selected Extras',
  noExtras: 'Standard Tier Only',
  hourlyRate: 'Standard Rate',
  additionalRoomsSurcharge: 'Scale Adjustment',
};

const arBase = {
  navHome: 'الرئيسية',
  navServices: 'خدماتنا',
  navWhyUs: 'لماذا نحن',
  navLogin: 'دخول الأعضاء',
  navLogout: 'تسجيل الخروج',
  heroTitle: 'تنظيف متميز لعقارات دبي الراقية',
  heroSubtitle: 'رفع مستوى الضيافة في عقارات العطلات مع اهتمام دقيق بالتفاصيل وجودة كونسيرج 5 نجوم.',
  heroCta: 'ابدأ الحجز',
  whyUsTitle: 'تميز نيتو كلينينج',
  whyUsPoints: [
    { title: 'ضمان الجودة', description: 'يتم التحقق من كل عملية تنظيف مقابل قائمة مراجعة ضيافة احترافية مكونة من 50 نقطة.' },
    { title: 'جدولة ديناميكية', description: 'منصتنا تتكامل بسلاسة مع تقويم الحجز الخاص بك لضمان الكفاءة الآلية.' },
    { title: 'مواد متميزة', description: 'استخدام حصري لمنتجات تعقيم عالية الجودة وصديقة للبيئة لسلامة الضيوف.' },
    { title: 'خبراء معتمدون', description: 'يتم فحص محترفي الضيافة لدينا بدقة، والتحقق من خلفياتهم وتأمينهم.' },
  ],
  servicesTitle: 'مستويات الخدمة المتخصصة',
  servicesSubtitle: 'حلول هندسية دقيقة لمضيفي الإيجار قصير الأمد المتميزين.',
  getQuote: 'طلب عرض سعر',
  footerText: `© ${new Date().getFullYear()} نيتو كلينينج الإمارات. مرخص من دائرة السياحة. جميع الحقوق محفوظة.`,
  whatsappMessage: 'تحية طيبة. أنا مهتم باستكشاف خدمات التنظيف الاحترافية لعقاري.',
  whatsappTooltip: 'هل تحتاج إلى عرض سعر؟ تحدث مع الكونسيرج الخاص بنا.',
  bookingTitle: 'تقدير فوري للخدمة',
  serviceType: 'مستوى التنظيف',
  bedrooms: 'غرف النوم',
  bathrooms: 'الحمامات',
  kitchens: 'المطابخ',
  otherRooms: 'صالة / أخرى',
  propertyDetails: 'مواصفات العقار',
  propertyRequirementsDesc: 'حدد متطلبات عقارك للتخصيص الدقيق.',
  estimatedPrice: 'الاستثمار التقديري',
  bookNow: 'المتابعة للحجز',
  howItWorksTitle: 'عمليتنا المبسطة',
  howItWorksSteps: [
      { title: 'الاختيار', description: 'حدد متطلباتك واحصل على تقدير فوري وشفاف للتكلفة.' },
      { title: 'التأكيد', description: 'أنهِ تفاصيلك عبر بوابتنا الآمنة أو مباشرة مع فريق الكونسيرج.' },
      { title: 'التنفيذ', description: 'يقدم محترفونا بيئة نظيفة، مما يضمن أن عقارك جاهز للضيوف.' }
  ],
  testimonialsTitle: 'تجارب المضيفين',
  testimonials: [
      { quote: 'لقد غيرت نيتو كلينينج عملياتي بشكل جذري. تناسقهم واحترافيتهم متميزون حقاً.', author: 'فاطمة الم.', location: 'محفظة مرسى دبي' },
      { quote: 'الاهتمام بالتفاصيل لافت للنظر. وضعي كمضيف متميز يعود الفضل فيه إلى معايير خدمتهم المثالية.', author: 'ماركوس ت.', location: 'مضيف نخلة جميرا' },
      { quote: 'كفاءة وموثوقية ودقة. إنهم يفهمون الفروق الدقيقة في الضيافة الفاخرة تماماً.', author: 'بريا ك.', location: 'أجنحة داون تاون' }
  ],
  footerServices: 'العروض',
  footerCompany: 'المؤسسة',
  footerAbout: 'قصتنا',
  footerContact: 'الكونسيرج',
  footerFollow: 'التواجد الاجتماعي',
  loginTitle: 'مرحباً بعودتك',
  loginSubtitle: 'قم بتوثيق جلستك عبر التحقق من واتساب.',
  loginPhoneLabel: 'رقم الاتصال',
  loginPhonePlaceholder: '50 123 4567',
  loginSendOtp: 'إرسال رمز التحقق',
  loginSendingOtp: 'جاري المعالجة...',
  loginOtpTitle: 'التحقق من الهوية',
  loginOtpSubtitle: 'أدخل الرمز الآمن المرسل إلى هاتفك المحمول.',
  loginOtpLabel: 'رمز الأمان',
  loginOtpPlaceholder: '123456',
  loginVerifyOtp: 'توثيق',
  loginVerifyingOtp: 'جاري التحقق...',
  loginSuccess: 'تم التوثيق. جاري التوجيه...',
  loginError: 'فشل التحقق. يرجى إعادة التأكد من التفاصيل.',
  bookingPageTitle: 'إنهاء طلب الخدمة',
  bookingSummary: 'ملخص الخدمة',
  detailsLabel: 'التفاصيل',
  cleaningHours: 'الوقت المخصص',
  howManyHours: 'المدة (ساعات)',
  numberOfProfessionals: 'عدد الموظفين',
  haveCleaningMaterials: 'هل تتوفر مواد التنظيف في الموقع؟',
  yes: 'نعم، متوفرة',
  no: 'لا، مطلوبة',
  specialInstructions: 'متطلبات العميل / رموز الدخول',
  specialInstructionsPlaceholder: 'رموز الدخول، مناطق التركيز، أو الأسطح الحساسة...',
  confirmBooking: 'إرسال الطلب',
  backToHome: 'رجوع',
  step1: 'المستوى والحجم',
  step2: 'التحسينات',
  step3: 'الخدمات اللوجستية',
  step4: 'التأكيد',
  step5: 'تم بنجاح',
  customizeService: 'تخصيص الخدمة',
  additionalServices: 'خدمات إضافية',
  scheduleAndDetails: 'الجدول والتفاصيل',
  reviewAndConfirm: 'التحقق النهائي',
  nextStep: 'استمرار',
  previousStep: 'رجوع',
  add: 'اختيار',
  added: 'مختار',
  scheduleYourCleaning: 'لوجستيات الموعد',
  selectDate: 'التاريخ المفضل',
  selectTime: 'وقت الوصول',
  address: 'موقع الخدمة',
  addressPlaceholder: 'رقم الوحدة/الفيلة، البرج، اسم المجمع',
  detectLocation: 'استخدام الموقع الحالي',
  detectingLocation: 'جاري تحديد الموقع...',
  detectLocationError: 'الوصول إلى الموقع مقيد. يرجى الإدخال يدوياً.',
  mapViewTitle: 'خريطة منطقة الخدمة',
  payment: 'التأكيد',
  paymentDetails: 'معلومات الاتصال',
  creditCard: 'حساب موثق',
  cardName: 'اسم جهة الاتصال',
  cardNamePlaceholder: 'اسمك الكامل',
  cardNumber: 'رقم الواتساب',
  cardNumberPlaceholder: '50 123 4567',
  cardExpiry: 'هاتف ثانوي',
  cardExpiryPlaceholder: 'اختياري',
  cardCVC: 'البريد الإلكتروني',
  cardCVCPlaceholder: 'manager@property.com',
  billingAddress: 'تفاصيل الطلب',
  country: 'المنطقة',
  countryPlaceholder: 'الإمارات العربية المتحدة',
  streetAddress: 'ملاحظات إضافية',
  streetAddressPlaceholder: 'أي شيء آخر يجب أن نعرفه؟',
  city: 'المدينة',
  cityPlaceholder: 'دبي',
  zipCode: 'الرمز البريدي',
  zipCodePlaceholder: '00000',
  reviewYourBooking: 'تم إرسال الطلب',
  totalPrice: 'إجمالي الاستثمار',
  cleaningDate: 'التاريخ',
  cleaningTime: 'الوقت',
  extras: 'الإضافات المختارة',
  noExtras: 'المستوى القياسي فقط',
  hourlyRate: 'السعر القياسي',
  additionalRoomsSurcharge: 'تعديل الحجم',
};

export const TRANSLATIONS: Translations = {
  [Language.EN]: enBase,
  [Language.AR]: arBase,
};

export const SERVICE_PACKAGES: ServicePackage[] = [
  {
    id: 'turnover',
    nameKey: 'turnover_name',
    priceKey: 'turnover_price',
    pricePeriodKey: 'turnover_period',
    descriptionKey: 'turnover_desc',
    featuresKey: [
      'turnover_feat1',
      'turnover_feat2',
      'turnover_feat3',
      'turnover_feat4',
      'turnover_feat5',
    ],
    popular: true,
  },
  {
    id: 'deep_clean',
    nameKey: 'deep_clean_name',
    priceKey: 'deep_clean_price',
    pricePeriodKey: 'deep_clean_period',
    descriptionKey: 'deep_clean_desc',
    featuresKey: [
      'deep_clean_feat1',
      'deep_clean_feat2',
      'deep_clean_feat3',
      'deep_clean_feat4',
      'deep_clean_feat5',
    ],
  },
  {
    id: 'essentials',
    nameKey: 'essentials_name',
    priceKey: 'essentials_price',
    pricePeriodKey: 'essentials_period',
    descriptionKey: 'essentials_desc',
    featuresKey: [
      'essentials_feat1',
      'essentials_feat2',
      'essentials_feat3',
      'essentials_feat4',
    ],
  },
];

export const SERVICE_TRANSLATIONS: ServicePackageTranslations = {
    turnover_name: { en: 'Executive Turnover', ar: 'تنظيف التبديل التنفيذي' },
    turnover_price: { en: 'AED 250', ar: '250 د.إ' },
    turnover_period: { en: '/ base', ar: '/ أساسي' },
    turnover_desc: { en: 'Rapid precision cleaning designed for seamless guest transitions.', ar: 'تنظيف دقيق سريع مصمم لتبديل الضيوف بسلاسة.' },
    turnover_feat1: { en: 'Hotel-standard sanitation', ar: 'تعقيم بمعايير الفنادق' },
    turnover_feat2: { en: 'Amenity replenishment', ar: 'تجديد المستلزمات' },
    turnover_feat3: { en: 'Linen culinary presentation', ar: 'تنسيق الشراشف الفاخر' },
    turnover_feat4: { en: 'High-traffic disinfection', ar: 'تطهير المناطق المزدحمة' },
    turnover_feat5: { en: '50-Point integrity audit', ar: 'تدقيق جودة من 50 نقطة' },
    deep_clean_name: { en: 'Elite Deep Clean', ar: 'تنظيف عميق متميز' },
    deep_clean_price: { en: 'AED 450', ar: '450 د.إ' },
    deep_clean_period: { en: '/ base', ar: '/ أساسي' },
    deep_clean_desc: { en: 'Comprehensive restoration of your property to immaculate standards.', ar: 'استعادة شاملة لممتلكاتك إلى معايير مثالية.' },
    deep_clean_feat1: { en: 'Detailed surface restoration', ar: 'ترميم الأسطح المفصل' },
    deep_clean_feat2: { en: 'Appliance deep sanitization', ar: 'تعقيم عميق للأجهزة' },
    deep_clean_feat3: { en: 'Upholstery steam care', ar: 'العناية بالبخار للمفروشات' },
    deep_clean_feat4: { en: 'Grout & tile refresh', ar: 'تجديد الجص والبلاط' },
    deep_clean_feat5: { en: 'Window & track detailing', ar: 'تفصيل النوافذ والمسارات' },
    essentials_name: { en: 'Restock & Prep', ar: 'إعادة التعبئة والتحضير' },
    essentials_price: { en: 'AED 150', ar: '150 د.إ' },
    essentials_period: { en: '/ visit', ar: '/ زيارة' },
    essentials_desc: { en: 'Essential amenity management for consistently stocked properties.', ar: 'إدارة المستلزمات الأساسية للعقارات المزودة باستمرار.' },
    essentials_feat1: { en: 'Toiletry replenishment', ar: 'تجديد مستلزمات الحمام' },
    essentials_feat2: { en: 'Welcome kit assembly', ar: 'تجميع مجموعة الترحيب' },
    essentials_feat3: { en: 'Manual/Guide verification', ar: 'التحقق من الدليل الإرشادي' },
    essentials_feat4: { en: 'Inventory reporting', ar: 'إعداد تقارير المخزون' },
    ironing_name: { en: 'Express Ironing', ar: 'كوي سريع' },
    balcony_cleaning_name: { en: 'Outdoor Terrace Scrub', ar: 'تنظيف الشرفة الخارجية' },
    fridge_cleaning_name: { en: 'Internal Fridge Detail', ar: 'تنظيف الثلاجة من الداخل' },
    wardrobe_cleaning_name: { en: 'Wardrobe Organization', ar: 'تنظيم خزانة الملابس' },
    after_party_cleaning_name: { en: 'Post-Event Restoration', ar: 'تنظيف ما بعد الحفلات' },
};

export const ADDITIONAL_SERVICES: AdditionalService[] = [
    { id: 'ironing', nameKey: 'ironing_name', descriptionKey: 'ironing_desc', price: 50, image: 'https://images.unsplash.com/photo-1595505290943-315147829824?q=80&w=800' },
    { id: 'balcony_cleaning', nameKey: 'balcony_cleaning_name', descriptionKey: 'balcony_cleaning_desc', price: 40, image: 'https://images.unsplash.com/photo-1621283262227-28f0f23a6b8f?q=80&w=800' },
    { id: 'fridge_cleaning', nameKey: 'fridge_cleaning_name', descriptionKey: 'fridge_cleaning_desc', price: 30, image: 'https://images.unsplash.com/photo-1617454238218-473f4a3d7a8c?q=80&w=800' },
    { id: 'wardrobe_cleaning', nameKey: 'wardrobe_cleaning_name', descriptionKey: 'wardrobe_cleaning_desc', price: 45, image: 'https://images.unsplash.com/photo-1558959298-a352b2f0c33a?q=80&w=800' },
    { id: 'after_party_cleaning', nameKey: 'after_party_cleaning_name', descriptionKey: 'after_party_cleaning_desc', price: 100, image: 'https://images.unsplash.com/photo-1543818399-ff3c177a4353?q=80&w=800' },
];