import { Language, Translations, ServicePackage, ServicePackageTranslations, AdditionalService } from './types';

export const WHATSAPP_NUMBER = "971501234567";
export const HOURLY_RATE_AED = 50;

export const LANGUAGES = {
  [Language.EN]: { nativeName: 'English', flag: '🇬🇧' },
  [Language.AR]: { nativeName: 'العربية', flag: '🇦🇪' },
};

export const COUNTRY_CODES = [
    { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪' },
    { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦' },
    { name: 'United Kingdom', code: '+44', flag: '🇬🇧' },
    { name: 'United States', code: '+1', flag: '🇺🇸' },
];

const enBase = {
  navHome: 'Home',
  navServices: 'Services',
  navWhyUs: 'Why Us',
  navLogin: 'Book Now',
  navLogout: 'Sign Out',
  heroTitle: 'Bespoke Cleaning for Dubai’s Premier Airbnbs',
  heroSubtitle: 'Elevating the standard of vacation rental hospitality with meticulous attention to detail and 5-star concierge quality.',
  heroCta: 'Initialize Booking',
  whyUsTitle: 'The NeatoCleaning Distinction',
  whyUsPoints: [
    { title: 'Quality Assurance', description: 'Every service is verified against a rigorous 50-point professional hospitality checklist.' },
    { title: 'Dynamic Scheduling', description: 'Our platform integrates seamlessly with your booking calendar for automated efficiency.' },
    { title: 'Premium Botanicals', description: 'Exclusively using high-grade, eco-conscious sanitization products for guest safety.' },
    { title: 'Certified Experts', description: 'Our hospitality professionals are extensively vetted, background-checked, and insured.' },
  ],
  servicesTitle: 'Specialized Services',
  servicesSubtitle: 'Precision-engineered solutions for the discerning property owner.',
  getQuote: 'Request Quote',
  footerText: `© ${new Date().getFullYear()} NeatoCleaning UAE. Licensed by DTCM. All rights reserved.`,
  whatsappMessage: 'Greetings. I am interested in exploring your professional cleaning services for my property.',
  whatsappTooltip: 'Need an instant quote? Chat with our concierge.',
  bookingTitle: 'Instant Service Estimate',
  serviceType: 'Cleaning Tier',
  bedrooms: 'Bedrooms',
  bathrooms: 'Bathrooms',
  kitchens: 'Kitchens',
  otherRooms: 'Lounge/Other',
  propertyDetails: 'Property Specifications',
  propertyRequirementsDesc: 'Define your property requirements for precise allocation.',
  estimatedPrice: 'Estimated Investment',
  bookNow: 'Proceed to Booking',
  howItWorksTitle: 'Our Streamlined Process',
  howItWorksSteps: [
      { title: 'Selection', description: 'Define your requirements and receive an immediate, transparent cost projection.' },
      { title: 'Confirmation', description: 'Finalize your details via our secure portal or directly with our concierge team.' },
      { title: 'Execution', description: 'Our professionals deliver a pristine environment, ensuring your property is guest-ready.' }
  ],
  testimonialsTitle: 'Host Experiences',
  aboutUsTitle: 'Our Story',
  aboutUsText: 'NeatoCleaning was born out of a passion for hospitality and a recognition of the unique demands of Dubai\'s short-term rental market. We understand that in the world of Airbnb, first impressions are everything. Our mission is to empower property owners by providing meticulous, hotel-standard cleaning and management services that guarantee guest satisfaction and Superhost status.',
  aboutUsStats: [
    { label: 'Properties Managed', value: '500+' },
    { label: 'Successful Cleanings', value: '15k+' },
    { label: 'Average Guest Rating', value: '4.9/5' },
    { label: 'Concierge Support', value: '24/7' },
  ],
  aboutUsServicesTitle: 'Comprehensive Hospitality Solutions',
  aboutUsServices: ['Meticulous Airbnb Cleanings', 'Elite Deep Cleaning', 'Amenity & Inventory Management', '24/7 Concierge Support'],
  testimonials: [
      { quote: 'NeatoCleaning has fundamentally transformed my operations. Their consistency and professionalism are truly elite.', author: 'Fatima Al M.', location: 'Dubai Marina Portfolio' },
      { quote: 'The attention to detail is remarkable. My Superhost status is largely thanks to their impeccable service standards.', author: 'Markus T.', location: 'Palm Jumeirah Host' },
      { quote: 'Efficient, reliable, and thorough. They understand the nuances of luxury hospitality perfectly.', author: 'Priya K.', location: 'Downtown Suites' }
  ],
  footerServices: 'Offerings',
  footerCompany: 'Enterprise',
  footerAbout: 'Our Story',
  footerContact: 'Concierge',
  footerFollow: 'Social Presence',
  loginTitle: 'Welcome Back',
  loginSubtitle: 'Authenticate your session via WhatsApp verification.',
  loginPhoneLabel: 'Contact Number',
  loginPhonePlaceholder: '50 123 4567',
  loginSendOtp: 'Send Verification Code',
  loginSendingOtp: 'Processing...',
  loginOtpTitle: 'Verify Identity',
  loginOtpSubtitle: 'Enter the secure code sent to your mobile device.',
  loginOtpLabel: 'Security Code',
  loginOtpPlaceholder: '123456',
  loginVerifyOtp: 'Authenticate',
  loginVerifyingOtp: 'Verifying...',
  loginSuccess: 'Authorized. Redirecting...',
  loginError: 'Authentication failed. Please re-verify your details.',
  bookingPageTitle: 'Finalize Service Request',
  bookingSummary: 'Service Summary',
  detailsLabel: 'Details',
  cleaningHours: 'Allocated Time',
  howManyHours: 'Duration (Hours)',
  numberOfProfessionals: 'Staff Count',
  haveCleaningMaterials: 'On-site Equipment Available?',
  yes: 'Yes, Provided',
  no: 'No, Required',
  specialInstructions: 'Property Notes / Access Codes',
  specialInstructionsPlaceholder: 'e.g. Access codes, parking spot, specific focus areas...',
  confirmBooking: 'Submit Inquiry',
  backToHome: 'Return',
  step1: 'Tier & Scale',
  step2: 'Enhancements',
  step3: 'Logistics',
  step4: 'Verification',
  step5: 'Success',
  customizeService: 'Refine Service',
  additionalServices: 'Add-on Services',
  scheduleAndDetails: 'Schedule & Logistics',
  reviewAndConfirm: 'Final Verification',
  nextStep: 'Continue',
  previousStep: 'Back',
  add: 'Select',
  added: 'Selected',
  scheduleYourCleaning: 'Appointment Logistics',
  selectDate: 'Preferred Date',
  selectTime: 'Arrival Window',
  address: 'Service Location',
  addressPlaceholder: 'Unit/Villa, Tower, Community Name',
  detectLocation: 'Use Current Location',
  detectingLocation: 'Locating...',
  detectLocationError: 'Location access restricted. Please input manually.',
  mapViewTitle: 'Service Zone Map',
  payment: 'Confirmation',
  paymentDetails: 'Contact Information',
  creditCard: 'Verified Account',
  cardName: 'Contact Name',
  cardNamePlaceholder: 'YOUR FULL NAME',
  cardNumber: 'WhatsApp Number',
  cardNumberPlaceholder: '50 123 4567',
  cardExpiry: 'Secondary Phone',
  cardExpiryPlaceholder: 'Optional',
  cardCVC: 'Email Address',
  cardCVCPlaceholder: 'manager@property.com',
  billingAddress: 'Inquiry Details',
  country: 'Region',
  countryPlaceholder: 'United Arab Emirates',
  streetAddress: 'Special Instructions',
  streetAddressPlaceholder: 'Anything else our team should know?',
  city: 'City',
  cityPlaceholder: 'Dubai',
  zipCode: 'Postal Code',
  zipCodePlaceholder: '00000',
  reviewYourBooking: 'Inquiry Submitted',
  totalPrice: 'Investment Total',
  cleaningDate: 'Date',
  cleaningTime: 'Time',
  extras: 'Selected Extras',
  noExtras: 'Standard Tier Only',
  hourlyRate: 'Standard Rate',
  additionalRoomsSurcharge: 'Scale Adjustment',
};

const arBase = {
  navHome: 'الرئيسية',
  navServices: 'خدماتنا',
  navWhyUs: 'لماذا نحن',
  navLogin: 'احجز الآن',
  navLogout: 'تسجيل الخروج',
  heroTitle: 'تنظيف متميز لعقارات دبي الراقية',
  heroSubtitle: 'رفع مستوى الضيافة في عقارات العطلات مع اهتمام دقيق بالتفاصيل وجودة كونسيرج 5 نجوم.',
  heroCta: 'ابدأ الحجز',
  whyUsTitle: 'تميز نيتو كلينينج',
  whyUsPoints: [
    { title: 'ضمان الجودة', description: 'يتم التحقق من كل عملية تنظيف مقابل قائمة مراجعة ضيافة احترافية مكونة من 50 نقطة.' },
    { title: 'جدولة ديناميكية', description: 'منصتنا تتكامل بسلاسة مع تقويم الحجز الخاص بك لضمان الكفاءة الآلية.' },
    { title: 'مواد متميزة', description: 'استخدام حصري لمنتجات تعقيم عالية الجودة وصديقة للبيئة لسلامة الضيوف.' },
    { title: 'خبراء معتمدون', description: 'يتم فحص محترفي الضيافة لدينا بدقة، والتحقق من خلفياتهم وتأمينهم.' },
  ],
  servicesTitle: 'خدمات متخصصة',
  servicesSubtitle: 'حلول هندسية دقيقة لأصحاب العقارات المتميزين.',
  getQuote: 'طلب عرض سعر',
  footerText: `© ${new Date().getFullYear()} نيتو كلينينج الإمارات. مرخص من دائرة السياحة. جميع الحقوق محفوظة.`,
  whatsappMessage: 'تحية طيبة. أنا مهتم باستكشاف خدمات التنظيف الاحترافية لعقاري.',
  whatsappTooltip: 'هل تحتاج إلى عرض سعر؟ تحدث مع الكونسيرج الخاص بنا.',
  bookingTitle: 'تقدير فوري للخدمة',
  serviceType: 'مستوى التنظيف',
  bedrooms: 'غرف النوم',
  bathrooms: 'الحمامات',
  kitchens: 'المطابخ',
  otherRooms: 'صالة / أخرى',
  propertyDetails: 'مواصفات العقار',
  propertyRequirementsDesc: 'حدد متطلبات عقارك للتخصيص الدقيق.',
  estimatedPrice: 'الاستثمار التقديري',
  bookNow: 'المتابعة للحجز',
  howItWorksTitle: 'عمليتنا المبسطة',
  howItWorksSteps: [
      { title: 'الاختيار', description: 'حدد متطلباتك واحصل على تقدير فوري وشفاف للتكلفة.' },
      { title: 'التأكيد', description: 'أنهِ تفاصيلك عبر بوابتنا الآمنة أو مباشرة مع فريق الكونسيرج.' },
      { title: 'التنفيذ', description: 'يقدم محترفونا بيئة نظيفة، مما يضمن أن عقارك جاهز للضيوف.' }
  ],
  testimonialsTitle: 'تجارب المضيفين',
  aboutUsTitle: 'قصتنا',
  aboutUsText: 'ولدت نيتو كلينينج من شغف بالضيافة وإدراك للمتطلبات الفريدة لسوق الإيجار قصير الأمد في دبي. نحن ندرك أنه في عالم إير بي إن بي، الانطباعات الأولى هي كل شيء. مهمتنا هي تمكين أصحاب العقارات من خلال تقديم خدمات تنظيف وإدارة دقيقة بمعايير الفنادق تضمن رضا الضيوف وحالة المضيف المتميز.',
  aboutUsStats: [
    { label: 'عقار مدار', value: '500+' },
    { label: 'عملية تبديل ناجحة', value: '15k+' },
    { label: 'متوسط تقييم الضيوف', value: '4.9/5' },
    { label: 'دعم الكونسيرج', value: '24/7' },
  ],
  aboutUsServicesTitle: 'حلول ضيافة شاملة',
  aboutUsServices: ['عمليات تبديل دقيقة لإير بي إن بي', 'تنظيف عميق متميز', 'إدارة المستلزمات والمخزون', 'دعم كونسيرج على مدار الساعة'],
  testimonials: [
      { quote: 'لقد غيرت نيتو كلينينج عملياتي بشكل جذري. تناسقهم واحترافيتهم متميزون حقاً.', author: 'فاطمة الم.', location: 'محفظة مرسى دبي' },
      { quote: 'الاهتمام بالتفاصيل لافت للنظر. وضعي كمضيف متميز يعود الفضل فيه إلى معايير خدمتهم المثالية.', author: 'ماركوس ت.', location: 'مضيف نخلة جميرا' },
      { quote: 'كفاءة وموثوقية ودقة. إنهم يفهمون الفروق الدقيقة في الضيافة الفاخرة تماماً.', author: 'بريا ك.', location: 'أجنحة داون تاون' }
  ],
  footerServices: 'العروض',
  footerCompany: 'المؤسسة',
  footerAbout: 'قصتنا',
  footerContact: 'الكونسيرج',
  footerFollow: 'التواجد الاجتماعي',
  loginTitle: 'مرحباً بعودتك',
  loginSubtitle: 'قم بتوثيق جلستك عبر التحقق من واتساب.',
  loginPhoneLabel: 'رقم الاتصال',
  loginPhonePlaceholder: '50 123 4567',
  loginSendOtp: 'إرسال رمز التحقق',
  loginSendingOtp: 'جاري المعالجة...',
  loginOtpTitle: 'التحقق من الهوية',
  loginOtpSubtitle: 'أدخل الرمز الآمن المرسل إلى هاتفك المحمول.',
  loginOtpLabel: 'رمز الأمان',
  loginOtpPlaceholder: '123456',
  loginVerifyOtp: 'توثيق',
  loginVerifyingOtp: 'جاري التحقق...',
  loginSuccess: 'تم التوثيق. جاري التوجيه...',
  loginError: 'فشل التحقق. يرجى إعادة التأكد من التفاصيل.',
  bookingPageTitle: 'إنهاء طلب الخدمة',
  bookingSummary: 'ملخص الخدمة',
  detailsLabel: 'التفاصيل',
  cleaningHours: 'الوقت المخصص',
  howManyHours: 'المدة (ساعات)',
  numberOfProfessionals: 'عدد الموظفين',
  haveCleaningMaterials: 'هل تتوفر مواد التنظيف في الموقع؟',
  yes: 'نعم، متوفرة',
  no: 'لا، مطلوبة',
  specialInstructions: 'متطلبات العميل / رموز الدخول',
  specialInstructionsPlaceholder: 'رموز الدخول، مناطق التركيز، أو الأسطح الحساسة...',
  confirmBooking: 'إرسال الطلب',
  backToHome: 'رجوع',
  step1: 'المستوى والحجم',
  step2: 'التحسينات',
  step3: 'الخدمات اللوجستية',
  step4: 'التأكيد',
  step5: 'تم بنجاح',
  customizeService: 'تخصيص الخدمة',
  additionalServices: 'خدمات إضافية',
  scheduleAndDetails: 'الجدول والتفاصيل',
  reviewAndConfirm: 'التحقق النهائي',
  nextStep: 'استمرار',
  previousStep: 'رجوع',
  add: 'اختيار',
  added: 'مختار',
  scheduleYourCleaning: 'لوجستيات الموعد',
  selectDate: 'التاريخ المفضل',
  selectTime: 'وقت الوصول',
  address: 'موقع الخدمة',
  addressPlaceholder: 'رقم الوحدة/الفيلة، البرج، اسم المجمع',
  detectLocation: 'استخدام الموقع الحالي',
  detectingLocation: 'جاري تحديد الموقع...',
  detectLocationError: 'الوصول إلى الموقع مقيد. يرجى الإدخال يدوياً.',
  mapViewTitle: 'خريطة منطقة الخدمة',
  payment: 'التأكيد',
  paymentDetails: 'معلومات الاتصال',
  creditCard: 'حساب موثق',
  cardName: 'اسم جهة الاتصال',
  cardNamePlaceholder: 'اسمك الكامل',
  cardNumber: 'رقم الواتساب',
  cardNumberPlaceholder: '50 123 4567',
  cardExpiry: 'هاتف ثانوي',
  cardExpiryPlaceholder: 'اختياري',
  cardCVC: 'البريد الإلكتروني',
  cardCVCPlaceholder: 'manager@property.com',
  billingAddress: 'تفاصيل الطلب',
  country: 'المنطقة',
  countryPlaceholder: 'الإمارات العربية المتحدة',
  streetAddress: 'ملاحظات إضافية',
  streetAddressPlaceholder: 'أي شيء آخر يجب أن نعرفه؟',
  city: 'المدينة',
  cityPlaceholder: 'دبي',
  zipCode: 'الرمز البريدي',
  zipCodePlaceholder: '00000',
  reviewYourBooking: 'تم إرسال الطلب',
  totalPrice: 'إجمالي الاستثمار',
  cleaningDate: 'التاريخ',
  cleaningTime: 'الوقت',
  extras: 'الإضافات المختارة',
  noExtras: 'المستوى القياسي فقط',
  hourlyRate: 'السعر القياسي',
  additionalRoomsSurcharge: 'تعديل الحجم',
};

export const TRANSLATIONS: Translations = {
  [Language.EN]: enBase,
  [Language.AR]: arBase,
};

export const SERVICE_PACKAGES: ServicePackage[] = [
  {
    id: 'residential',
    nameKey: 'residential_name',
    priceKey: 'residential_price',
    pricePeriodKey: 'residential_period',
    descriptionKey: 'residential_desc',
    featuresKey: [
      'residential_feat1',
      'residential_feat2',
      'residential_feat3',
    ],
  },
  {
    id: 'airbnb',
    nameKey: 'airbnb_name',
    priceKey: 'airbnb_price',
    pricePeriodKey: 'airbnb_period',
    descriptionKey: 'airbnb_desc',
    featuresKey: [
      'airbnb_feat1',
      'airbnb_feat2',
      'airbnb_feat3',
    ],
    popular: true,
  },
  {
    id: 'deep_clean',
    nameKey: 'deep_clean_name',
    priceKey: 'deep_clean_price',
    pricePeriodKey: 'deep_clean_period',
    descriptionKey: 'deep_clean_desc',
    featuresKey: [
      'deep_clean_feat1',
      'deep_clean_feat2',
      'deep_clean_feat3',
    ],
  },
  {
    id: 'move_in_out',
    nameKey: 'move_in_out_name',
    priceKey: 'move_in_out_price',
    pricePeriodKey: 'move_in_out_period',
    descriptionKey: 'move_in_out_desc',
    featuresKey: [
      'move_in_out_feat1',
      'move_in_out_feat2',
      'move_in_out_feat3',
    ],
  },
  {
    id: 'office',
    nameKey: 'office_name',
    priceKey: 'office_price',
    pricePeriodKey: 'office_period',
    descriptionKey: 'office_desc',
    featuresKey: [
      'office_feat1',
      'office_feat2',
      'office_feat3',
    ],
  },
  {
    id: 'same_day',
    nameKey: 'same_day_name',
    priceKey: 'same_day_price',
    pricePeriodKey: 'same_day_period',
    descriptionKey: 'same_day_desc',
    featuresKey: [
      'same_day_feat1',
      'same_day_feat2',
      'same_day_feat3',
    ],
  },
];

export const SERVICE_TRANSLATIONS: ServicePackageTranslations = {
    residential_name: { en: 'Residential Cleaning', ar: 'تنظيف سكني' },
    residential_price: { en: 'AED 150', ar: '150 د.إ' },
    residential_period: { en: '/ visit', ar: '/ زيارة' },
    residential_desc: { en: 'Standard home cleaning for daily comfort and hygiene.', ar: 'تنظيف منزلي قياسي للراحة والنظافة اليومية.' },
    residential_feat1: { en: 'Dusting & vacuuming', ar: 'إزالة الغبار والكنس' },
    residential_feat2: { en: 'Kitchen & bathroom sanitization', ar: 'تعقيم المطبخ والحمام' },
    residential_feat3: { en: 'Floor mopping', ar: 'مسح الأرضيات' },
    
    airbnb_name: { en: 'Airbnb & Holiday Home', ar: 'تنظيف إير بي إن بي وبيوت العطلات' },
    airbnb_price: { en: 'AED 250', ar: '250 د.إ' },
    airbnb_period: { en: '/ turnover', ar: '/ تبديل' },
    airbnb_desc: { en: 'Professional turnover services for short-term rentals.', ar: 'خدمات تبديل احترافية للإيجارات قصيرة الأمد.' },
    airbnb_feat1: { en: 'Hotel-standard sanitation', ar: 'تعقيم بمعايير الفنادق' },
    airbnb_feat2: { en: 'Amenity replenishment', ar: 'تجديد المستلزمات' },
    airbnb_feat3: { en: 'Linen & towel setup', ar: 'تجهيز البياضات والمناشف' },
    
    deep_clean_name: { en: 'Deep Cleaning', ar: 'تنظيف عميق' },
    deep_clean_price: { en: 'AED 450', ar: '450 د.إ' },
    deep_clean_period: { en: '/ session', ar: '/ جلسة' },
    deep_clean_desc: { en: 'Thorough sanitization for a pristine environment.', ar: 'تعقيم شامل لبيئة نظيفة تماماً.' },
    deep_clean_feat1: { en: 'Detailed surface restoration', ar: 'ترميم الأسطح المفصل' },
    deep_clean_feat2: { en: 'Appliance deep sanitization', ar: 'تعقيم عميق للأجهزة' },
    deep_clean_feat3: { en: 'Grout & tile refresh', ar: 'تجديد الجص والبلاط' },
    
    move_in_out_name: { en: 'Move-in / Move-out', ar: 'تنظيف الانتقال (دخول/خروج)' },
    move_in_out_price: { en: 'AED 500', ar: '500 د.إ' },
    move_in_out_period: { en: '/ service', ar: '/ خدمة' },
    move_in_out_desc: { en: 'Detailed cleaning for property transitions.', ar: 'تنظيف مفصل لانتقالات العقارات.' },
    move_in_out_feat1: { en: 'Inside cabinet cleaning', ar: 'تنظيف الخزائن من الداخل' },
    move_in_out_feat2: { en: 'Window & track detailing', ar: 'تفصيل النوافذ والمسارات' },
    move_in_out_feat3: { en: 'Full property disinfection', ar: 'تطهير كامل للعقار' },
    
    office_name: { en: 'Office Cleaning', ar: 'تنظيف المكاتب' },
    office_price: { en: 'AED 300', ar: '300 د.إ' },
    office_period: { en: '/ visit', ar: '/ زيارة' },
    office_desc: { en: 'Professional workspace maintenance for productivity.', ar: 'صيانة احترافية لمساحة العمل من أجل الإنتاجية.' },
    office_feat1: { en: 'Desk & equipment sanitization', ar: 'تعقيم المكاتب والمعدات' },
    office_feat2: { en: 'Common area maintenance', ar: 'صيانة المناطق المشتركة' },
    office_feat3: { en: 'Waste management', ar: 'إدارة النفايات' },
    
    same_day_name: { en: 'Same-day Service', ar: 'خدمة في نفس اليوم' },
    same_day_price: { en: 'AED 350', ar: '350 د.إ' },
    same_day_period: { en: '/ request', ar: '/ طلب' },
    same_day_desc: { en: 'Urgent cleaning solutions when you need them most.', ar: 'حلول تنظيف عاجلة عندما تكون في أمس الحاجة إليها.' },
    same_day_feat1: { en: 'Priority scheduling', ar: 'جدولة ذات أولوية' },
    same_day_feat2: { en: 'Rapid response team', ar: 'فريق استجابة سريع' },
    same_day_feat3: { en: 'Comprehensive express clean', ar: 'تنظيف سريع شامل' },
};

export const ADDITIONAL_SERVICES: AdditionalService[] = [
    { id: 'ironing', nameKey: 'ironing_name', descriptionKey: 'ironing_desc', price: 50, image: 'https://images.unsplash.com/photo-1595505290943-315147829824?q=80&w=800' },
    { id: 'balcony_cleaning', nameKey: 'balcony_cleaning_name', descriptionKey: 'balcony_cleaning_desc', price: 40, image: 'https://images.unsplash.com/photo-1621283262227-28f0f23a6b8f?q=80&w=800' },
    { id: 'fridge_cleaning', nameKey: 'fridge_cleaning_name', descriptionKey: 'fridge_cleaning_desc', price: 30, image: 'https://images.unsplash.com/photo-1617454238218-473f4a3d7a8c?q=80&w=800' },
    { id: 'wardrobe_cleaning', nameKey: 'wardrobe_cleaning_name', descriptionKey: 'wardrobe_cleaning_desc', price: 45, image: 'https://images.unsplash.com/photo-1558959298-a352b2f0c33a?q=80&w=800' },
    { id: 'after_party_cleaning', nameKey: 'after_party_cleaning_name', descriptionKey: 'after_party_cleaning_desc', price: 100, image: 'https://images.unsplash.com/photo-1543818399-ff3c177a4353?q=80&w=800' },
];